language: python
python:
  - 3.6

services:
  - docker

install:
  - pip install -r requirements.txt
  - python manage.py -a update -t compose
  - docker-compose up --build -d

script:
  - docker ps | grep -q api
  - docker ps |grep -q redis-service
  - docker ps |grep -q mongodb
  - docker ps |grep -q api-socket
  - docker ps |grep -q compiler
  - docker ps |grep -q ui
  - docker ps |grep -q c2